# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'
language: node_js
node_js:
  - "8"

before_install:
  - docker build -t ramitmitra/stash-master .
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSERNAME" --password-stdin
  - docker push ramitmitra/stash-master
