# make use of vm's 
sudo: 'required'

# building only for these branches
branches:
  only:
  - master
  - vcs

# have the docker service set up
services:
  - 'docker'
language: node_js
node_js:
  - "8"

# build and push the docker image for stashmaster to docker hub
before_install:
  - docker build -t ramitmitra/stash-master .
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSERNAME" --password-stdin
  - docker push ramitmitra/stash-master
