version: "3.1"
services:
  stash-master:
    build: .
    image: ramitmitra/stash-master
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "80:2323"
      - "5055:5055"
      - "8080:8080"
    env_file:
    - docker.env
    # depends_on:
    #   - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  # redis:
  #   image: redis:alpine
  #   restart: on-failure
  #   stop_grace_period: 30s
  #   deploy:
  #     replicas: 2
  #     update_config:
  #       parallelism: 2
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure